name: Supabase Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrations:
    runs-on: ubuntu-latest

    environment: Production

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.162.4

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
